version: 0.2

phases:
  build:
    commands:
      - aws s3 sync ./ s3://${S3_Bucket} --delete --exclude '.git/*'
      - echo "Sync S3 bucket with repository - Successful"
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id ${CloudFront} --paths "/*"
      - echo "Cache invalidation - Successful"